# Generated by Django 4.1.6 on 2023-02-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10, verbose_name='販売価格')),
                ('location', models.CharField(max_length=50, verbose_name='所在地')),
                ('planOfHouse', models.CharField(max_length=5, verbose_name='間取り')),
                ('freedom', models.TextField(blank=True, null=True, verbose_name='その他の情報')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ1')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ1')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ1')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ1')),
            ],
        ),
    ]
