# Generated by Django 4.1.6 on 2023-02-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relator',
            name='price',
            field=models.IntegerField(verbose_name='販売価格'),
        ),
    ]
