# Generated by Django 4.1.6 on 2023-02-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_relator_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='ユーザー')),
                ('favorite_relator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.relator', verbose_name='お気に入りの物件')),
            ],
        ),
    ]
